update

diff --git a/bush/use_cc b/bush/use_cc
--- a/bush/use_cc
+++ b/bush/use_cc
@@ -58,6 +58,30 @@ elif [ ${build_clang} = "yes" ] ; then
     exit
   fi
 
+  if [ ${build_ansi} = "yes" ] ; then ccflags="${ccflags} -ansi"; fi
+  if [ ${build_pedantic} = "yes" ] ; then ccflags="${ccflags} -pedantic"; fi
+
+elif [ ${build_emcc} = "yes" ] ; then
+  config_name=emcc
+  
+  found=no
+  items="emcc"
+  for item in ${items} ; do
+    ${bush_home}/check_app ${item}
+    use_status=$?;
+    if [ ${use_status} = 0 ] ; then
+      cc_compiler=${item}
+      cc_linker=${item}
+      found=yes
+      break
+    fi
+  done
+
+  if [ ${found} = no ] ; then
+    echo "${items} not found."
+    exit
+  fi
+
 elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
 
   # options taken from the output of :
diff --git a/bush/use_cpp b/bush/use_cpp
--- a/bush/use_cpp
+++ b/bush/use_cpp
@@ -91,6 +91,27 @@ elif [ ${build_clang} = "yes" ] ; then
    #cppflags="${cppflags} -stdlib=libc++"
   fi
 
+elif [ ${build_emcc} = "yes" ] ; then
+  config_name=emcc
+
+  found=no
+  items="emcc"
+  for item in ${items} ; do
+    ${bush_home}/check_app ${item}
+    use_status=$?;
+    if [ ${use_status} = 0 ] ; then
+      cpp_compiler=${item}
+      cpp_linker=${item}
+      found=yes
+      break
+    fi
+  done
+  
+  if [ ${found} = no ] ; then
+    echo "${items} not found."
+    exit
+  fi
+
 elif [ ${build_cling_clang} = "yes" ] ; then
   config_name=cling_clang
 
